name: AuctionStorm
main: com.alchemi.as.AuctionStorm
authors: [Alchemi, martijnpu]
version: 1.0.1
description: Really nice auction plugin!
depend: [Vault, AlchemicLibrary]

commands:
    auc:
        description: AuctionStorm base command.
        usage: /auc
        aliases: [as, auctionstorm, auction]
    
    bid:
        description: Bid on the current auction.
        usage: /bid [bid] [secret bid]
        aliases: [as bid, auctionstorm bid, auc bid, auction bid]
        
    auc start:
        description: Start an auction using the item in hand.
        usage: /auc start <price> [amount] [increment] [duration]
        aliases: [as start, auctionstorm start, auction start, as s, auctionstorm s, auction s]
        
    auc help:
        description: Display the AuctionStorm help page.
        usage: /auc help
        aliases: [as help, auctionstorm help, auction help]
        
    auc info:
        description: Get info about the current auction.
        usage: /auc info
        aliases: [as info, auctionstorm info, auction info, as i, auctionstorm i, auction i]
        
    auc cancel:
        description: Cancel the current auction.
        usage: /auc cancel
        aliases: [as cancel, auctionstorm cancel, auction cancel, as end, auctionstorm end, auction end]
        
    asadmin:
        description: AuctionStorm admin command.
        usage: /asadmin
    
    asadmin return:
        description: Return items from the auction specified.
        usage: /asadmin return <seller> <all/item/money> <id>
        
    asadmin info:
        description: Get info about the specified auction.
        usage: /asadmin info seller <id>
        
    asadmin reload:
        description: Reload the config files.
        usage: /asadmin reload [config.yml]
        
    asadmin defaults:
        description: Reset the config files to default.
        usage: /asadmin defaults [config.yml]

permissions:
    as.*:
        description: Gives permissions for all AuctionStorm commands.
        children:
            as.base: true
            as.creative: true
            as.admin: true
            as.reload: true
            as.return: true
            as.defaults: true
            as.cancel: true
        default: false
    as.base:
        description: Base AuctionStorm permission.
        default: true
    as.creative:
        description: Permission to start an auction in creative.
        default: false
    as.admin:
        description: Permmision to use the admin command.
        default: false
    as.reload:
        description: Permission to reload the config files.
        default: false
    as.defaults:
        description: Permission to reset the config files.
        default: false
    as.return:
        description: Permission to refund auctions.
        default: false 
    as.cancel:
        description: Permission to cancel any and all auctions.
        default: false