name: AuctionStorm
main: com.alchemi.as.AuctionStorm
authors: [Alchemi, martijnpu]
version: ${project.version}
api-version: 1.13
description: Really nice auction plugin!
depend: [Vault, AlchemicLibrary]

commands:
    auc:
        description: AuctionStorm base command.
        usage: /auc
        aliases: [as, auctionstorm, auction]
    
    bid:
        description: Bid on the current auction.
        usage: /bid [bid] [secret bid]
        
    asadmin:
        description: AuctionStorm admin command.
        usage: /asadmin

permissions:
    as.*:
        description: Gives permissions for all AuctionStorm commands.
        children:
            as.base: true
            as.creative: true
            as.admin: true
            as.reload: true
            as.return: true
            as.defaults: true
            as.cancel: true
        default: false
    as.base:
        description: Base AuctionStorm permission.
        default: true
    as.creative:
        description: Permission to start an auction in creative.
        default: false
    as.admin:
        description: Permmision to use the admin command.
        default: false
    as.reload:
        description: Permission to reload the config files.
        default: false
    as.defaults:
        description: Permission to reset the config files.
        default: false
    as.return:
        description: Permission to refund auctions.
        default: false 
    as.cancel:
        description: Permission to cancel any and all auctions.
        default: false